AsistenciaDocente/routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\ImagenesControler;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
  

Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

Route::middleware('auth')->group(function ()
{
   Route::resource('/','ImagenesController');
   Route::resource('imagenes', 'ImagenesController');
   Route::resource('productos', 'ProductosController');
   Route::resource('marcas', 'MarcasController');
   Route::resource('categorias', 'CategoriasController');
   
});

AsistenciaDocente/app/Models/Marca.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Marca extends Model
{
	protected $primaryKey = 'id_marca';

    protected $table= 'marcas';

    protected $fillable = [
    'id_marca',  'nombre_marca', 'created_at', 'updated_at'
    ];

  	public function producto(){

    return $this->hasMany('app\Models\Producto');
  	
  	}
}

AsistenciaDocente/app/Http/Controllers/MarcasController.php
<?php

namespace App\Http\Controllers;
use App\Models\Producto;
use App\Models\Marca;
use App\Models\Categoria;
use Illuminate\Http\Request;
use App\Http\Requests\MarcaRequest;

class MarcasController extends Controller
{
    
    public function index()
    {
        
        $datos= Marca::all();
        return view('marcas/index')->with('datos', $datos);
    }

   
    public function create()
    {
        $datos = Marca::all();
        return view('marcas/create')->with('datos', $datos);
    }

    
    public function store(MarcaRequest $request)
    {
        
        if (Marca::create($request->all())) {
            return redirect()->route('marcas.index');
        }else{
            return back()->with('El producto no puede ser procesado!, vuelva a intentarlo');
        }
    }

    
    public function show(Marca $marca)
    {
        //
    }

    
    public function edit($marca)
    {
        $marca = Marca::findOrFail($marca);
        return view('marcas.edit')->with('marca', $marca);
    }

    
    public function update(MarcaRequest $request, $marca)
    {
        $this->validate($request, [
            'nombre_marca' => 'required', 
        ]);

        $marca = Marca::find($marca);

        $marca->nombre_marca = $request->nombre_marca;

        if ($marca->save()){
            return redirect()->route('marcas.index')->with('Datos guardados satisfactoriamente');
        }else{  
            return back()->with('El producto no puede ser procesado!, vuelva a intentarlo');
        }
    }

    
    public function destroy($marca)
    {
        $marca = Marca::findOrFail($marca);
        $marca->delete();
        
        if($marca->delete()){
            return redirect()->route('marcas.index')->with('success', 'La marca se ha eliminado correctamente');
        }else{
            return redirect()->route('marcas.index')->with('error', 'La marca no se ha podido eliminar');
        };

    }
}

AsistenciaDocente/resources/views/marcas/create.blade.php
@extends('layouts.app')
@section('content')

<!--productos.store hace referencia a la función store-->
<div class="row">
<form action="{{ route('marcas.store') }}" method="POST">
	{{ csrf_field() }}
	<fieldset>
		<legend>Nueva Marca</legend>

		<div class="mb-3">
			<label class="form-label">Nombre</label>
			<div>

				@if ($errors->has('nombre_marca'))
					<span style="color:red;">{{$errors->first('nombre_marca')}}</span>
				@endif

				<!--En name y id se pone el nombre de la BD-->
				<input type="text" name="nombre_marca" id="nombre_marca" placeholder="Nombre" class="form-control">	
			</div>
		</div>
		<br>
		<div style="text-align:center;">
			<button type="submit" class="btn btn-primary">Agregar</button>
			<a href="/marcas" class="btn btn-info">Cancelar</a>
		</div>
	</fieldset>
</form>
</div>
@endsection

AsistenciaDocente/resources/views/marcas/edit.blade.php
@extends('layouts.app')
@section('content')

<form action="{{ route('marcas.update', $marca->id_marca) }}" method="POST">
	<input type="hidden" name="_method" value="PUT">
		{{ csrf_field() }}

	<fieldset>
		<legend>Editar Marca</legend>

		<div class="mb-3">
			<label class="form-label">Nombre</label>
			<div>

				@if ($errors->has('nombre_marca'))
					<span style="color:red;">{{$errors->first('nombre_marca')}}</span>
				@endif
				
				<!--En name y id se pone el nombre de la BD-->
				<input type="text" name="nombre_marca" id="nombre_marca" value='{{$marca->nombre_marca}}' class="form-control">	
			</div>
		</div>
		<br>
		<div style="text-align:center;">
			<button type="submit" class="btn btn-primary">Actualizar</button>
			<a href="/marcas" class="btn btn-info">Cancelar</a>
		</div>

	</fieldset>
</form>
@endsection

AsistenciaDocente/resources/views/marcas/index.blade.php
@extends('layouts.app')
@section('content')

<div class="row">

	<table class="table table-sm">
		
		<div style="text-align:center">
			<h1>Indice de Marcas</h1>
		</div>

		<thead>
			<tr>
				<th>Id</th>
				<th>Nombre</th>
				<th>Acciones</th>
				<th><a href="/marcas/create" class="btn btn-success">Agregar</a></th>
			</tr>
		</thead>

		<tbody>
			<!--Bucle for-->
			@foreach ($datos as $marca)
			<tr>
				<td>{{$marca->id_marca}}</td>
				<td>{{$marca->nombre_marca}}</td>
				<td><a href="{{route('marcas.edit', ['marca' => $marca->id_marca])}}" class="btn btn-warning">Modificar</a></td>
				<td>
					<form action="{{ route('marcas.destroy', $marca->id_marca) }}" method="POST">
						{{ csrf_field() }}
						{{ method_field('DELETE') }}
						<button type="submit" class="btn btn-danger" onclick="return confirm('Estas seguro de eliminar la marca? Esto es irreversible.')">Eliminar</button>
					</form>
				</td>
			</tr>
			@endforeach

		</tbody>

	</table>

</div>  
@endsection    

        
     