AsistenciaDocente/routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\ImagenesControler;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
  

Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

Route::middleware('auth')->group(function ()
{
   Route::resource('/','ImagenesController');
   Route::resource('imagenes', 'ImagenesController');
   Route::resource('productos', 'ProductosController');
   Route::resource('marcas', 'MarcasController');
   Route::resource('categorias', 'CategoriasController');
   
});

AsistenciaDocente/app/Models/Producto.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Producto extends Model
{
  protected $primaryKey = 'id_producto';

  protected $table= 'productos';

  protected $fillable = [
    'id_producto',  'nombre_producto', 'precio_producto', 'categorias_id_categoria', 'marcas_id_marca', 'imagenes_id_imagen', 'created_at', 'updated_at'
  ];

  public function marcas(){

    return $this->belongsTo('app\Models\Marca');
  }
  
  public function categorias(){

    return $this->belongsTo('app\Models\Categoria');
  }

  public function producto(){
    return $this->hasMany('app\Models\Imagen');
  }
    
}

AsistenciaDocente/app/Http/Controllers/ProductosController.php
<?php

namespace App\Http\Controllers;
use App\Models\Producto;
use App\Models\Marca;
use App\Models\Categoria;
use App\Models\Imagen;
use Illuminate\Http\Request;
use App\Http\Requests\ProductoRequest;
use Illuminate\Support\Facades\Redirect;

class ProductosController extends Controller
{

    public function index()  //Consulta SQL a la BD
    {
            

        $datos = Producto::select('productos.id_producto','productos.nombre_producto as producto', 'productos.precio_producto', 'marcas.nombre_marca as marca', 'categorias.nombre_categoria as categoria')
            ->join('marcas','marcas.id_marca','=','productos.marcas_id_marca')
            ->join('categorias', 'categorias.id_categoria','=','productos.categorias_id_categoria')
            ->get();

        return view('productos/index')->with('datos', $datos);
    }

    public function create() //Crear un nuevo Registro
    {
        $datosMarca=Marca::all();
        $datosCategoria=Categoria::all();

        return view('productos/create')->with('datosMarca', $datosMarca)->with('datosCategoria', $datosCategoria);
    }


    public function store(ProductoRequest $request) //Guarda el registro en la BD
    {
        


        if($request->hasFile('image')){
            $file = $request->file('image');
            $fileName = time().'.'.$file->getClientOriginalName();
            $path = public_path('/images/productos/');
            $file->move($path,$fileName);
            
                
            $dato = new Producto($request->all());
            $dato -> save();

            $image = new Imagen();
            $image -> nombre_imagen = $fileName;
            $image -> producto()->associate($dato);
            $image -> save();
        }else{
            $dato = new Producto($request->all());
            $dato -> save();
        }


        return redirect()->route('productos.index'); 
    }


    public function show(Producto $producto)
    {
        //
    }

    public function edit($producto)
    {
        $marca = Marca::all();
        $categoria = Categoria::all();
        $imagen = Imagen::all();
        $producto = Producto::findOrFail($producto);
        return view('productos.edit')->with('marca', $marca)->with('producto', $producto)->with('imagen',$imagen)->with('categoria', $categoria);
    }


    public function update(ProductoRequest $request, $producto)
    {
        $this->validate($request, [
            'nombre_producto' => 'required', 
            'precio_producto' => 'required',
        ]);

        $producto = Producto::find($producto);

            $producto->nombre_producto = $request->nombre_producto;
            $producto->precio_producto = $request->precio_producto;
            $producto->marcas_id_marca = $request->marcas_id_marca;
            $producto->categorias_id_categoria = $request->categorias_id_categoria;

        if ($producto->save()){
            return redirect()->route('productos.index')->with('Datos guardados satisfactoriamente');
        }else{  
            return back()->with('El producto no puede ser procesado!, vuelva a intentarlo');
        }
    }


    public function destroy($producto)
    {
        $producto = Producto::findOrFail($producto);
        $producto->delete();
        if($producto->delete()){
            return redirect()->route('productos.index')->with('success', 'El producto se ha eliminado correctamente');
        }else{
            return redirect()->route('productos.index')->with('error', 'El producto no se ha podido eliminar');
        };
        
    }
}

AsistenciaDocente/resources/views/productos/create.blade.php
@extends('layouts.app')
@section('content')

<!--productos.store hace referencia a la función store-->
<form action="{{ route('productos.store') }}" enctype="multipart/form-data" method="POST">
	{{ csrf_field() }}
	<fieldset>
		<legend>Nuevo Producto</legend>

		<div class="mb-3">
			<label class="form-label">Nombre</label>
			<div>
				
				@if ($errors->has('nombre_producto'))
					<span style="color:red;">{{$errors->first('nombre_producto')}}</span>
				@endif

				<!--En name y id se pone el nombre de la BD-->
				<input type="text" name="nombre_producto" id="nombre_producto" placeholder="Nombre" class="form-control">	
			</div>
		</div>

		<div class="mb-3">
			<label class="form-label">Precio</label>
			<div>

				@if ($errors->has('precio_producto'))
					<span style="color:red;">{{$errors->first('precio_producto')}}</span>
				@endif

				<!--El type aquí será number-->
				<input type="number" name="precio_producto" id="precio_producto" placeholder="Precio" class="form-control">
			</div>
		</div>

	
		<div class="mb-3">
			<label class="form-label">Seleccione la marca</label>
			<div>
				<!--El id en este caso será "select" porque hace referencia a la cajita que tenemos-->
				<!--Aquí se usa el nombre de la tabla Producto-->
				<select id="select" name="marcas_id_marca" class="form-control">
					@foreach ($datosMarca as $marca)
						<!--Aquí se usan los nombres de la tabla Marca-->
						<option value="{{$marca->id_marca}}">{{$marca->nombre_marca}}</option>
					@endforeach
				</select>
			</div>
		</div>

		<div class="mb-3">
			<label class="form-label">Seleccione la categoria</label>
			<div>
				<!--El id en este caso será "select" porque hace referencia a la cajita que tenemos-->
				<!--Aquí se usa el nombre de la tabla Producto-->
				<select id="select" name="categorias_id_categoria" class="form-control">
					@foreach ($datosCategoria as $categoria)
						<!--Aquí se usan los nombres de la tabla Marca-->
						<option value="{{$categoria->id_categoria}}">{{$categoria->nombre_categoria}}</option>
					@endforeach
				</select>
			</div>
		</div>
		

		<div>
			<label for="photo">Agregar Imagen</label>
			<div class="input-group">
				<input type="file" class="form-control" name="image" aria-describedby="inputGroupFileAddon04" arial-label="Upload">
			</div>
		</div>

		<br>

		<div style="text-align:center;">
			<button type="submit" class="btn btn-success">Guardar</button>
			<a href="/productos" class="btn btn-info">Cancelar</a>
		</div>

	</fieldset>
</form>
@endsection

AsistenciaDocente/resources/views/productos/edit.blade.php
@extends('layouts.app')
@section('content')

<form action="{{ route('productos.update', $producto->id_producto) }}" method="POST">
	<input type="hidden" name="_method" value="PUT">
		{{ csrf_field() }}
	
	<fieldset>
		<legend>Editar Producto</legend>

		<div class="mb-3">
			<label class="form-label">Nombre</label>
			<div>

				@if ($errors->has('nombre_producto'))
					<span style="color:red;">{{$errors->first('nombre_producto')}}</span>
				@endif

				<!--En name y id se pone el nombre de la BD-->
				<input type="text" name="nombre_producto" id="nombre_producto" value='{{$producto->nombre_producto}}' class="form-control">	
			</div>
		</div>

		<div class="mb-3">
			<label class="form-label">Precio</label>
			<div>

				@if ($errors->has('precio_producto'))
					<span style="color:red;">{{$errors->first('precio_producto')}}</span>
				@endif
				
				<!--El type aquí será number-->
				<input type="number" name="precio_producto" id="precio_producto" value='{{$producto->precio_producto}}' class="form-control">
			</div>
		</div>

		<div class="mb-3">
			<label class="form-label">Seleccione la marca</label>
			<select class="form-control" id="select" name="marcas_id_marca">
				@foreach ($marca as $marca)
					@if ($marca->id_marca == $producto->marcas_id_marca)
						<option selected value="{{$marca->id_marca}}">{{$marca->nombre_marca}}</option>
					@else
						<option value="{{$marca->id_marca}}">{{$marca->nombre_marca}}</option>
					@endif
				@endforeach
			</select>
		</div>

		<div class="mb-3">
			<label class="form-label">Seleccione la Categoria</label>
			<select class="form-control" id="select" name="categorias_id_categoria">
				@foreach ($categoria as $categoria)
					@if ($categoria->id_categoria == $producto->categorias_id_categoria)
						<option selected value="{{$categoria->id_categoria}}">{{$categoria->nombre_categoria}}</option>
					@else
						<option value="{{$categoria->id_categoria}}">{{$categoria->nombre_categoria}}</option>
					@endif
				@endforeach
			</select>
		</div>
		<br>

		
		<div style="text-align:center;">
			<button type="submit" class="btn btn-primary">Actualizar</button>
			<a href="/productos" class="btn btn-info">Cancelar</a>
		</div>
	</fieldset>
</form>
@endsection

AsistenciaDocente/resources/views/productos/index.blade.php
@extends('layouts.app')
@section('content')

<div class="row">
	<table class="table table-sm">

		<div style="text-align:center">
			<h1>Indice de Productos</h1>
		</div>
		
		<thead class="thead-dark">
			<tr>
				<th>Id</th>
				<th>Nombre</th>
				<th>Precio</th>
				<th>Marca</th>
				<th>Categoria</th>
				<th>Acciones</th>
				<th><a href="/productos/create" class="btn btn-success">Agregar</a></th>
			</tr>
		</thead>

		<tbody>
			<!--Bucle for-->
			@foreach ($datos as $producto)
			<tr>
				<td>{{$producto->id_producto}}</td>
				<td>{{$producto->producto}}</td>
				<td>{{$producto->precio_producto}}</td>
				<td>{{$producto->marca}}</td>
				<td>{{$producto->categoria}}</td>
				<td><a href="{{route('productos.edit', ['producto' => $producto->id_producto])}}" class="btn btn-warning">Modificar</a></td>
				<td>
					<form action="{{ route('productos.destroy', $producto->id_producto) }}" method="POST">
						{{ csrf_field() }}
						{{ method_field('DELETE') }}
						<button type="submit" class="btn btn-danger" onclick="return confirm('Estas seguro de eliminar el producto? Esto es irreversible.')">Eliminar</button>
					</form>
				</td>
			</tr>
			@endforeach
		</tbody>
	
	</table>
</div>      
@endsection
        
     