AsistenciaDocente/routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\ImagenesControler;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
  

Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

Route::middleware('auth')->group(function ()
{
   Route::resource('/','ImagenesController');
   Route::resource('imagenes', 'ImagenesController');
   Route::resource('productos', 'ProductosController');
   Route::resource('marcas', 'MarcasController');
   Route::resource('categorias', 'CategoriasController');
   
});

AsistenciaDocente/app/Models/Categoria.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Categoria extends Model
{
    protected $primaryKey = 'id_categoria';

    protected $table= 'categorias';

    protected $fillable = [
    'id_categoria',  'nombre_categoria', 'created_at', 'updated_at'];

  public function productos(){

    return $this->hasMany('app\Models\Producto');
    }
}

AsistenciaDocente/app/Http/Controllers/CategoriasController.php
<?php

namespace App\Http\Controllers;
use App\Models\Producto;
use App\Models\Categoria;
use App\Models\Marca;
use Illuminate\Http\Request;
use App\Http\Requests\CategoriaRequest;

class CategoriasController extends Controller
{
   
    public function index()
    {
        $datos= Categoria::all();
        return view('categorias/index')->with('datos', $datos);
    }

    
    public function create()
    {
        $datos = Categoria::all();
        return view('categorias/create')->with('datos', $datos);
    }

    
    public function store(CategoriaRequest $request)
    {
        
        if (Categoria::create($request->all())) {
           return redirect()->route('categorias.index');
        }else{
            return back()->with('El producto no puede ser procesado!, vuelva a intentarlo');
        }
    }

    
    public function show(Categorias $categoria)
    {
        //
    }

    
    public function edit($categoria)
    {
        $categoria = Categoria::findOrFail($categoria);
        return view('categorias.edit')->with('categoria', $categoria);
    }

   
    public function update(CategoriaRequest $request, $categoria)
    {
        $this->validate($request, [
            'nombre_categoria' => 'required', 
        ]);

        $categoria = Categoria::find($categoria);

        $categoria->nombre_categoria = $request->nombre_categoria;

        if ($categoria->save()){
            return redirect()->route('categorias.index')->with('Datos guardados satisfactoriamente');
        }else{  
            return back()->with('El producto no puede ser procesado!, vuelva a intentarlo');
        }
    }

    
    public function destroy($categoria)
    {
        $categoria = Categoria::findOrFail($categoria);
        $categoria->delete();
        if($categoria->delete()){
            return redirect()->route('categorias.index')->with('success', 'La categoria se ha eliminado correctamente');
        }else{
            return redirect()->route('categorias.index')->with('error', 'La categoria no se ha podido eliminar');
        };
    }
}

AsistenciaDocente/resources/views/categorias/create.blade.php
@extends('layouts.app')
@section('content')

<!--productos.store hace referencia a la función store-->
<form action="{{ route('categorias.store') }}" method="POST">
	{{ csrf_field() }}
	<fieldset>
		<legend>Nueva Categoria</legend>

		<div class="mb-3">
			<label class="form-label">Nombre</label>
			<div>

				@if ($errors->has('nombre_categoria'))
					<span style="color:red;">{{$errors->first('nombre_categoria')}}</span>
				@endif

				<!--En name y id se pone el nombre de la BD-->
				<input type="text" name="nombre_categoria" id="nombre_categoria" placeholder="Nombre" class="form-control">	
			</div>
		</div>
		<br>
		<div style="text-align:center;">
			<button type="submit" class="btn btn-primary">Agregar</button>
			<a href="/categorias" class="btn btn-info">Cancelar</a>
		</div>

	</fieldset>
</form>
@endsection    

AsistenciaDocente/resources/views/categorias/edit.blade.php
@extends('layouts.app')
@section('content')

<form action="{{ route('categorias.update', $categoria->id_categoria) }}" method="POST">
	<input type="hidden" name="_method" value="PUT">
		{{ csrf_field() }}
	
	<fieldset>
		<legend>Editar Categoria</legend>

		<div class="mb-3">
			<label class="form-label">Nombre</label>
			<div>

				@if ($errors->has('nombre_categoria'))
					<span style="color:red;">{{$errors->first('nombre_categoria')}}</span>
				@endif

				<!--En name y id se pone el nombre de la BD-->
				<input type="text" name="nombre_categoria" id="nombre_categoria" value='{{$categoria->nombre_categoria}}' class="form-control">	
			</div>
		</div>
		<br>
		<div style="text-align:center;">
			<button type="submit" class="btn btn-primary">Actualizar</button>
			<a href="/categorias" class="btn btn-info">Cancelar</a>
		</div>

	</fieldset>
</form>
@endsection    

AsistenciaDocente/resources/views/categorias/index.blade.php
@extends('layouts.app')
@section('content')

<div class="row">

		<table class="table table-sm" >

		<div style="text-align:center">
			<h1>Indice de Categorias</h1>
		</div>

		<thead class="thead-dark">
			<tr>
				<th>Id</th>
				<th>Nombre</th>
				<th>Acciones</th>
				<th><a href="/categorias/create" class="btn btn-success">Agregar</a></th>
			</tr>
		</thead>

		<tbody>
			<!--Bucle for-->
			@foreach ($datos as $categoria)
			<tr>
				<td>{{$categoria->id_categoria}}</td>
				<td>{{$categoria->nombre_categoria}}</td>
				<td><a href="{{route('categorias.edit', ['categoria' => $categoria->id_categoria])}}" class="btn btn-warning">Modificar</a></td>
				<td>
					<form action="{{ route('categorias.destroy', $categoria->id_categoria) }}" method="POST">
						{{ csrf_field() }}
						{{ method_field('DELETE') }}
						<button type="submit" class="btn btn-danger" onclick="return confirm('Estas seguro de eliminar la categoria? Esto es irreversible.')">Eliminar</button>
					</form>
				</td>
			</tr>
			@endforeach
		</tbody>
	
	</table>
</div>      
@endsection    

        
     